<?php

namespace Akela\Bundle\CoreBundle\Repository;

/**
 * InstalmentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstalmentsRepository extends \Doctrine\ORM\EntityRepository
{
}
