akela_admin_home:
    path:       /dashboard
    defaults:   { _controller: AdminBundle:Default:index }

akela_admin_invoice:
    path:       /invoice/{invoice_id}
    defaults:   { _controller: AdminBundle:Default:invoice }

#email_verification:
#    path:       /verify/{uid}/{hash}
#    defaults:   { _controller: AdminBundle:Security:verify, uid: 0, hash: 0 }
#    methods:    [GET]
#    requirements:
#        uid:    \d+
#        hash:   "[a-fA-F0-9]*"
#
#email_resend_verification:
#    path:       /resend_verify_email
#    defaults:   { _controller: AdminBundle:Security:resendVerificationEmail }
#    methods:    [POST]
#
#email_is_verified:
#    path:       /verified_email
#    defaults:   { _controller: AdminBundle:Security:isVerifiedEmail }
#    methods:    [GET,POST]
#
#forgot_password:
#    path:       /forgot_password
#    defaults:   { _controller: AdminBundle:Security:forgotPassword }
#    methods:    [GET,POST]
#
#forgot_password_token:
#    path:       /forgot_password/send_token
#    defaults:   { _controller: AdminBundle:Security:sendPasswordToken }
#    methods:    [POST]
#
#forgot_password_sent:
#    path:       /forgot_password/email_sent
#    defaults:    { _controller: AdminBundle:Default:forgotPasswordEmail }
#
#forgot_password_reset:
#    path:       /reset_password/{token}
#    defaults:   { _controller: AdminBundle:Security:resetPassword, token: 0 }
#    methods:    [GET,POST]
#    requirements:
#        token:  "[a-fA-F0-9]*"
