akela_home:
#    path: /
#    defaults:   { _controller: PublicBundle:Public:index }
    resource: "@PublicBundle/Resources/config/routing.yml"

#akela_admin:
#    resource: "@AdminBundle/Resources/config/routing.yml"

akela_user:
    resource: "@PackBundle/Resources/config/routing.yml"

webroot:
    path: /
    defaults:   { _controller: PackBundle:Security:login }