# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    akela.security.login_form_authenticator:
        class: Akela\Bundle\PackBundle\Security\LoginFormAuthenticator
        autowire: true

    akela.doctrine.hash_password_listener:
        class: Akela\Bundle\PackBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }