akela_user_home:
    path:       /
    defaults:   { _controller: UserBundle:User:index }

akela_user_show:
    path:       /student
    defaults:   { _controller: UserBundle:User:show }

akela_user_edit:
    path:       /student/edit/{id}
    defaults:   { _controller: UserBundle:User:edit }
    methods:    [GET,PUT]

akela_user_add:
    path:       /student/add
    defaults:   { _controller: UserBundle:User:add }
    methods:    [GET,POST]

akela_user_add:
    path:       /student/search
    defaults:   { _controller: UserBundle:User:search }
    methods:    [GET,POST]

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#
#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#
#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"