akela_user_home:
    path:       /
    defaults:   { _controller: UserBundle:User:index }

akela_security_login:
    path:       /login
    defaults:   { _controller: UserBundle:Security:login }

akela_security_logout:
    path:       /logout
    defaults:   { _controller: UserBundle:Security:logout }

akela_user_show:
    path:       /student
    defaults:   { _controller: UserBundle:User:show }

akela_user_add:
    path:       /student/add
    defaults:   { _controller: UserBundle:User:add }

akela_user_edit:
    path:       /student/edit/{id}
    defaults:   { _controller: UserBundle:User:edit }
    methods:    [GET,PUT]


akela_user_search:
    path:       /student/search
    defaults:   { _controller: UserBundle:User:search }
    methods:    [GET,POST]